import type { Metadata } from "next";
import { Geist_Mono, Open_Sans } from "next/font/google";
import Header from "@/components/header/Header";
import Providers from "./providers";
import { CartProvider } from "@/contexts/CartContext";
import { ToastProvider } from "@/contexts/ToastContext";
import "./globals.css";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${geistMono.variable} antialiased bg-surface text-on-surface`}
      >
        <Providers>
          <CartProvider>
            <ToastProvider>
              <div className="flex min-h-screen w-full justify-center">
                <main className="flex h-full w-full max-w-[1080px] flex-1 pt-0">
                  <div className="flex w-full justify-center">
                    <div className="w-full min-w-[360px] max-w-[1080px]">
                      <Header />
                      {children}
                    </div>
                  </div>
                </main>
              </div>
            </ToastProvider>
          </CartProvider>
        </Providers>
      </body>
    </html>
  );
}
